tests

diff --git a/.github/workflows/integrationtests.yml b/.github/workflows/integrationtests.yml
--- a/.github/workflows/integrationtests.yml
+++ b/.github/workflows/integrationtests.yml
@@ -67,7 +67,24 @@ jobs:
     - name: Install SU2
       shell: bash -l {0}
       run: installation/Ubuntu/install_su2.sh
-        
+
+    - name: Print directory structure
+      run: |
+        echo "Current directory structure:"
+        ls -R
+
+    - name: Check if forces_breakdown.dat exists
+      run: |
+        if [ ! -f forces_breakdown.dat ]; then
+          echo "forces_breakdown.dat is missing!"
+          exit 1
+        else
+          echo "forces_breakdown.dat found."
+        fi
+    
+    - name: Print environment variables
+      run: printenv
+      
     - name: Run integration tests
       shell: bash -l {0}
       run: |
